services:
  app:
    build: .
    container_name: poc_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./src/storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache
    command: sh -lc "mkdir -p storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs bootstrap/cache && chown -R www-data:www-data storage bootstrap/cache && php-fpm"
    depends_on:
      - db

  web:
    image: nginx:1.25-alpine
    container_name: poc_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: poc_db
    environment:
      POSTGRES_DB: poc
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    image: node:20-alpine
    container_name: poc_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - app

volumes:
  pgdata:
  laravel_cache: